parameters:
#    product_category.example.class: SITE\ProductCategoryBundle\Example

services:
#    product_category.example:
#        class: %product_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
