cms_banner_homepage:
    pattern:  /cms_banner
    defaults: { _controller: CMSBannerBundle:Default:index }

CMSBannerBundle_cms_banner:
        resource: "@CMSBannerBundle/Resources/config/routing/banner.yml"
        prefix:   /cms/banner