site_representantes_homepage:
    pattern:  /representantes
    defaults: { _controller: SITERepresentantesBundle:Default:index }

site_representantes_get_regioes:
    pattern:  /representantes/regioes
    defaults: { _controller: SITERepresentantesBundle:Default:getRegioes }
    requirements: { _method: post }

site_representantes_get_representantes:
    pattern:  /representantes/representantes
    defaults: { _controller: SITERepresentantesBundle:Default:getRepresentantes }
    requirements: { _method: post }

site_representantes_js_ajax:
    pattern:  /representantes/js/representantes.js
    defaults: { _controller: SITERepresentantesBundle:Default:js_ajax }
