CMS\ProductBundle\Entity\Acabamento:
    type: entity
    table: acabamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
