CMS\ProductBundle\Entity\Pantone:
    type: entity
    table: pantone
    repositoryClass: CMS\ProductBundle\Entity\PantoneRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        hex:
            type: string
            nullable: false
            length: 6
            fixed: true
            comment: ''
        red:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        green:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        blue:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
            gedmo:
                timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                on: update
        isActive:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: is_active
    lifecycleCallbacks: {  }
