CMS\ProductBundle\Entity\ProductCategory:
    type: entity
    table: product_category
    repositoryClass: CMS\ProductBundle\Entity\ProductCategoryRepository
    indexes:
        fk_product_category_product_category1_idx:
            columns:
                - parent_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        slug:
            type: string
            length: 128
            nullable: false
            gedmo:
                slug:
                    separator: -
                    fields:
                      - name
                    updatable: true
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        image:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
            gedmo:
                timestampable:
                  on: create
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                  on: update
        isActive:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: is_active
    manyToOne:
        parent:
            targetEntity: ProductCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: productCategory
    lifecycleCallbacks: {  }
