<?php

namespace CMS\RepresentanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteRepository extends EntityRepository
{
    public function getEstados()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM CMSConfiguracoesBundle:Estado e
                WHERE e.id IN ( SELECT es.id FROM CMSRepresentanteBundle:Representante r INNER JOIN r.estado es )
                ORDER BY e.nome ASC'
            )
            ->getResult();
    }

    public function getCidadesByUF($estado)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM CMSConfiguracoesBundle:Cidade c
                WHERE c.id IN ( SELECT cid.id FROM CMSRepresentanteBundle:Representante r
                    INNER JOIN r.estado es
                    INNER JOIN r.cidade cid
                    WHERE es.sigla = \'' . $estado . '\')
                ORDER BY c.nome ASC'
            )
            ->getResult();
    }



    public function search($estado, $cidade = null)
    {

        $SQL = 'SELECT r FROM CMSRepresentanteBundle:Representante r
                    INNER JOIN r.estado es
                    INNER JOIN r.cidade cid
                    WHERE es.sigla = \'' . $estado . '\'';

        if(!is_null($cidade))
        {
            $SQL .= ' AND cid.nome = \'' . $cidade . '\'';
        }

        return $this->getEntityManager()
            ->createQuery($SQL)
            ->getResult();
    }
}
