<?php

namespace CMS\RepresentanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteRepository extends EntityRepository
{
    public function getEstados()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM CMSConfiguracoesBundle:Estado e
                WHERE e.id IN ( SELECT es.id FROM CMSRepresentanteBundle:Representante r INNER JOIN r.estado es )
                ORDER BY e.nome ASC'
            )
            ->getResult();
    }

    public function getCidadesByUF($sigla)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c 
                             FROM CMSConfiguracoesBundle:Cidade c
                            WHERE c.id IN (SELECT cid.id 
                                             FROM CMSRepresentanteBundle:Representante r
                                       INNER JOIN r.estado es
                                       INNER JOIN r.cidade cid
                                            WHERE es.sigla = ?1)
                         ORDER BY c.nome ASC'
            )
            ->setParameter(1, $sigla)
            ->getResult();
    }



    public function getRepresentantesByCidade($cidade)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r 
                             FROM CMSRepresentanteBundle:Representante r
            INNER JOIN r.cidade c
                 WHERE c.id = ?1')
            ->setParameter(1, $cidade)
            ->getResult();
    }
}
