CMS\CoresBundle\Entity\Color:
    type: entity
    table: color
    indexes:
        fk_color_pantone1_idx:
            columns:
                - pantone_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        image:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        hexadecimal:
            type: string
            nullable: true
            length: 6
            fixed: true
            comment: ''
        code:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                  on: create
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
            gedmo:
              timestampable:
                  on: update
        isActive:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: is_active
    manyToOne:
        pantone:
            targetEntity: \CMS\PantoneBundle\Entity\Pantone
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pantone_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
