parameters:
#    cms_contato.example.class: CMS\ContatoBundle\Example

services:
#    cms_contato.example:
#        class: %cms_contato.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
