<?php

namespace CMS\ConfiguracoesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegiaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegiaoRepository extends EntityRepository
{
}
