contato_homepage:
    pattern:  /contato
    defaults: { _controller: ContatoBundle:Default:index }

contato_send:
    pattern:  /contato/send
    defaults: { _controller: ContatoBundle:Default:send }
