parameters:
#    contato.example.class: SITE\ContatoBundle\Example

services:
#    contato.example:
#        class: %contato.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
