parameters:
#    cms_representante.example.class: CMS\RepresentanteBundle\Example

services:
#    cms_representante.example:
#        class: %cms_representante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
