<?php

namespace CMS\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRelatedRepository extends EntityRepository
{
}
