parameters:
#    site_page.example.class: SITE\PageBundle\Example

services:
#    site_page.example:
#        class: %site_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
