parameters:
#    cms_pantone.example.class: CMS\PantoneBundle\Example

services:
#    cms_pantone.example:
#        class: %cms_pantone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
