parameters:
#    cms_product_fields.example.class: CMS\ProductFieldsBundle\Example

services:
#    cms_product_fields.example:
#        class: %cms_product_fields.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
